### ISSUE TITLE
Running the test suite fails.

### ISSUE THREAD

**Issue by 573** [WJWH/shorturls#2]
Inside WSL I am getting the following when building:

> Preprocessing test suite 'shorturls-test' for shorturls-0.1.0.0...
[1 of 1] Compiling Main             ( test/Spec.hs, dist/build/shorturls-test/shorturls-test-tmp/Main.dyn_o )
Linking dist/build/shorturls-test/shorturls-test ...
running tests
Running 1 test suites...
Test suite shorturls-test: RUNNING...
shorturls-test: Network.Socket.connect: <socket: 40>: does not exist (Connection refused)
Test suite shorturls-test: FAIL
Test suite logged to: dist/test/shorturls-0.1.0.0-shorturls-test.log
0 of 1 test suites (0 of 1 test cases) passed.

Can you tell what to consider in that case?

Note:  
> ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=128 time=0.405 ms

**Comment by WJWH** [comment]
Do you have a local redis instance running (on the default port)? The error message is not very clear in what it's connecting to, but it's probably that :slightly_smiling_face:

**Comment by 573** [comment]
@WJWH that was it. With the redis-server running it works.
